// Purpose: Verify packing, aggregation, candidates, absence, provenance and estimates.
import test from'node:test';import assert from'node:assert/strict';import{packingPlan,aggregate,candidates,extract,estimate,FakeJev,validateSchema}from'../src/index.mjs';
const schema={fields:{email:{kind:'candidate',description:'Contact email',candidate_pattern:'[\\w.+-]+@[\\w.-]+\\.[A-Za-z]{2,}',absent:true},urgent:{kind:'flag',description:'Urgent',aggregate:'any'}}};
test('packing stays within and oversized question errors',()=>{const p=packingPlan([{id:'a',instructions:'x'.repeat(10)},{id:'b',instructions:'y'.repeat(10)}],10,{combinedLimit:100,safety:20});assert.equal(p.length,2);assert.throws(()=>packingPlan([{id:'x',instructions:'z'.repeat(100)}],1,{combinedLimit:20,safety:1}),/larger/)});
test('aggregation rules and tie',()=>{const v=[{value:true,probability:.6},{value:false,probability:.9}];assert.equal(aggregate(v,'first'),v[0]);assert.equal(aggregate(v,'any'),true);assert.equal(aggregate(v,'all'),false);assert.equal(aggregate(v,'max_probability'),v[1]);assert.equal(aggregate(v,'majority'),false)});
test('candidate absence and offsets',async()=>{assert.deepEqual(candidates('nothing','[0-9]+'),[]);const text='mail a@b.co now',fake=new FakeJev({email__present:{value:true,probability:.9},email:{value:'a@b.co',probability:.8},urgent:{value:false,probability:.7}});const r=await extract(schema,text,fake);assert.equal(r.record.email,'a@b.co');const c=r.provenance.email[0].candidate;assert.equal(text.slice(c.start,c.end),'a@b.co')});
test('absent yields null',async()=>{const f=new FakeJev({email__present:{value:false,probability:.9},email:{value:null,probability:.5}});assert.equal((await extract(schema,'none',f)).record.email,null)});
test('estimate request count matches run',async()=>{const text='a@b.co';const e=estimate(schema,text);const r=await extract(schema,text,new FakeJev());assert.equal(e.requestCount,r.usage.requests)});
test('free text rejected with candidate hint',()=>assert.throws(()=>validateSchema({fields:{x:{kind:'text'}}}),/candidate/));
