// Purpose: Candidate-only schema compilation, packing, chunk aggregation and provenance.
import {createHash} from 'node:crypto';
export const PRICE=.042;
export const canonical=v=>JSON.stringify(v,Object.keys(v??{}).sort());
export const hash=v=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
export function candidates(text,pattern='auto'){const specs=pattern==='auto'?[['email',/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g],['date',/\b\d{4}-\d{2}-\d{2}\b/g],['amount',/[$€£]\s?\d+(?:[.,]\d{2})?/g],['identifier',/\b[A-Z]{2,}-\d+\b/g]]:[[pattern,new RegExp(pattern,'g')]];return specs.flatMap(([kind,re])=>[...text.matchAll(re)].map(m=>({kind,value:m[0],start:m.index,end:m.index+m[0].length})));}
export function validateSchema(schema){for(const [id,f] of Object.entries(schema.fields??{})){if(!['enum','flag','level','candidate'].includes(f.kind))throw new Error(`Field ${id}: free text is unsupported; use kind=candidate with candidate_pattern`);if(f.kind==='candidate'&&!f.candidate_pattern)throw new Error(`Field ${id}: candidate_pattern is required`);if(!['first','any','all','max_probability','majority'].includes(f.aggregate??'max_probability'))throw new Error(`Field ${id}: invalid aggregate`);}return schema;}
export function compile(schema,text){validateSchema(schema);const qs=[];for(const [id,f] of Object.entries(schema.fields)){let options=f.values;if(f.kind==='candidate')options=candidates(text,f.candidate_pattern).map(x=>x.value);if(f.absent)qs.push({id:`${id}__present`,field:`${id}__present`,type:'noul',instructions:`Is ${f.description} stated at all?`});qs.push({id,field:id,type:f.kind==='flag'?'noul':f.kind==='level'?'score':'choice',instructions:f.description,criteria:options,candidates:f.kind==='candidate'?candidates(text,f.candidate_pattern):undefined});}return qs;}
export function packingPlan(questions,stateChars,{requestLimit=64000,combinedLimit=32000,safety=2000}={}){const limit=Math.min(requestLimit,combinedLimit)-safety;if(stateChars>limit)throw new Error('State exceeds packing budget and must be chunked');const packs=[];let pack=[],used=stateChars;for(const q of questions){const size=JSON.stringify(q).length;if(stateChars+size>limit)throw new Error(`Question ${q.id} is larger than the packing budget`);if(used+size>limit){packs.push(pack);pack=[];used=stateChars;}pack.push(q);used+=size;}if(pack.length)packs.push(pack);return packs;}
export function chunks(text,maxChars=24000){const out=[];for(let i=0;i<text.length;i+=maxChars)out.push({text:text.slice(i,i+maxChars),start:i});return out.length?out:[{text:'',start:0}];}
export function aggregate(values,rule){if(!values.length)return null;if(rule==='first')return values[0];if(rule==='any')return values.some(x=>x.value);if(rule==='all')return values.every(x=>x.value);if(rule==='max_probability')return [...values].sort((a,b)=>b.probability-a.probability)[0];const counts=new Map;for(const x of values)counts.set(x.value,(counts.get(x.value)??0)+1);return [...counts].sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0])))[0][0];}
export function estimate(schema,text,opts={}){const pieces=chunks(text,opts.chunkChars),plans=pieces.map(c=>packingPlan(compile(schema,c.text),c.text.length,opts));const questions=compile(schema,text).length;const requests=plans.reduce((n,p)=>n+p.length,0);const tokens=Math.ceil(pieces.reduce((n,c)=>n+c.text.length,0)/4)*Math.max(1,requests);return{questionCount:questions,requestCount:requests,packingRatio:questions/requests,estimatedInputTokens:tokens,estimatedCostUsd:tokens*PRICE/1e6,naiveCostUsd:Math.ceil(text.length/4)*questions*PRICE/1e6};}
export class FakeJev{constructor(fixtures={}){this.fixtures=fixtures;this.calls=[]}async judge(state,questions){this.calls.push({state,questions});return Object.fromEntries(questions.map(q=>[q.id,this.fixtures[q.id]??{value:q.type==='noul'?true:q.criteria?.[0]??0,probability:.8}]))}}
export async function extract(schema,text,provider=new FakeJev(),opts={}){const output={},provenance={};let request=0;for(const [chunkIndex,chunk] of chunks(text,opts.chunkChars).entries()){const qs=compile(schema,chunk.text);for(const pack of packingPlan(qs,chunk.text.length,opts)){const answers=await provider.judge({text:chunk.text},pack);for(const q of pack){const a=answers[q.id];(output[q.field]??=[]).push({value:a.value,probability:a.probability,chunk:chunkIndex,request,candidate:q.candidates?.find(x=>x.value===a.value)});}request++;}}const record={};for(const [id,f] of Object.entries(schema.fields)){const present=output[id+'__present'];if(f.absent&&present&&!aggregate(present,'max_probability').value){record[id]=null;provenance[id]=present;continue;}const selected=aggregate(output[id]??[],f.aggregate??'max_probability');record[id]=selected?.value??null;provenance[id]=output[id]??[];}return{record,provenance,usage:{requests:request},cacheKey:hash({schema,text})};}
